### ISSUE TITLE
compiling & linking against system curl which version is much lower.

### ISSUE THREAD

**Issue by liushiqi9** [hedronvision/bazel-make-cc-https-easy#26]
Commit Version: b339f0d2eae4577ecb8e34da577c2af5afccdb36
OS: Centos 8.5.2111
g++: 12.2.0
bazel: 5.2.0
curl: 7.82.0
libcur-devel l:libcurl-devel-7.61.1-22.el8.x86_64

Following the instruction from the Readme. I installed libcurl-devel through dnf which gives me curl 7.82.0.
When I compile some binary depend on `@cpr`, the cpr will include `curl/curl.h` from `/usr/include/curl/curl.h` which version is much lower than neede. Compile will return error: 

```
external/cpr/include/cpr/util.h: In function 'int cpr::util::progressUserFunction(const T*, cpr::cpr_pf_arg_t, cpr::cpr_pf_arg_t, cpr::cpr_pf_arg_t, cpr::cpr_pf_arg_t)':
external/cpr/include/cpr/util.h:26:36: error: 'CURL_PROGRESSFUNC_CONTINUE' was not declared in this scope
   26 |     static_assert(cancel_retval != CURL_PROGRESSFUNC_CONTINUE);
```

**Comment by cpsauer** [comment]
Hey @liushiqi9--sorry I'm just seeing this. Any chance you can just pull a newer dev version of libcurl through your OS?

**Comment by liushiqi9** [comment]
libcur-devel Only have 7.61 on centos 8.  https://pkgs.org/download/libcurl-devel

**Comment by cpsauer** [comment]
@liushiqi9, isn't the right solution for centos 8 to instead support a more recent version, since curl is *such* a common package? Wish I had the bandwidth to workaround or do, but I don't right now, unfortunately, so I'll close. But if you think I'm wrong, please write back and I'll reopen.
