### ISSUE TITLE
[Self-Filed] Linux Support

### ISSUE THREAD

**Issue by cpsauer** [hedronvision/bazel-make-cc-https-easy#6]
This is a tracking issue for Linux builds, linked to from the README.

If you'd like support for Linux, we'd love your help. It should be a fair bit easier to add support than to do yourself from scratch, we'll help guide, and then your code will work across platforms for free. Plus, you'll be helping everyone out. Please comment here, helping ensure people don't duplicate efforts.

**Comment by cpsauer** [comment]
Sketch of how to implement:

CPR should just work out of the box, so the focus will be on getting configuration for libCURL. Basically, you just grab the [latest curl release](https://github.com/curl/curl/releases), run ./configure to generate curl_config.h for your platform, and then add any different flags for your platform to [curl.BUILD](curl.BUILD), referencing the guiding comments therein.

(Note that most Linux distributions don't bundle libcurl by default, so we'll want to build it with Bazel rather than just link against a .so. Arch does, but not Ubuntu, Debian, Redhat, CentOS See https://everything.curl.dev/get/linux)

In more detail:
- I doubt the curl_configure.h will be *that* different from Android. Just diff what's defined in yours and in curl.BUILD, adding to the selects for whatever is not parallel.
- Please link to system libssl/crypto/z, assuming they're shipped with the OS.
- The key thing will be pointing to the CA bundles or path on your platform. For that, I'd just take a quick peek at the autodetect logic for CA bundles in https://github.com/curl/curl/blob/master/CMakeLists.txt (see CURL_CA_PATH_AUTODETECT), and figure out where it is for your OS. The Bazel OS values are in https://github.com/bazelbuild/platforms/blob/main/os/BUILD. Please run some quick tests against https://badssl.com.

**Comment by xivarri** [comment]
Hi! Thanks for addressing https://github.com/hedronvision/bazel-make-cc-https-easy/issues/10, sorry for the delayed response (holidays and all), but I'd be happy to help guinea-pig linux support. 
After updating to the latest version, the new error I get is 

```
configurable attribute "deps" in @curl//:source doesn't match this configuration. Would a default condition help?

Conditions checked:
 @platforms//os:android
 @platforms//os:macos
 @platforms//os:ios
 @platforms//os:tvos
 @platforms//os:watchos

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @curl//:source has configuration identifier 620947e. To inspect its configuration, run: bazel config 620947e.

For more help, see https://docs.bazel.build/configurable-attributes.html#why-doesnt-my-select-choose-what-i-expect.
```

On running `bazel run 620947e`, I just get 
```
INFO: Displaying config with id 620947e
ERROR: No configuration found with ID prefix 620947e
```

**Comment by cpsauer** [comment]
Hey, @xivarri!

That one was expected! It was Bazel telling you that Linux wasn't yet supported in the select (basically a switch on platforms).

After some more thought, I decided we should probably depend on a system-installed libcurl for linux, since (unlike the other supported platforms) it (usually) has a functional package management system built-in that's used for distribution, so it's probably better to get and share libcurl on the system than to bundle standalone apps.

Anyway, just landed support. Could you try putting the latest commit into your WORKSPACE, installing the libcurl development headers with `sudo apt-get install libcurl4-openssl-dev` (Debian/Ubuntu) or the equivalent for your distribution. (For install instructions for other distributions, see libcurl entries here: https://everything.curl.dev/get/linux.)
Please let me know how it goes! I want it to work for you :)

(And I get it; holidaying and overloaded, too!)

Cheers,
Chris

**Comment by xivarri** [comment]
That works! Thanks a bunch!

**Comment by cpsauer** [comment]
Yay! I'm so glad. Thanks for writing in.
